### ISSUE TITLE
Scorpius Core Initial Build

### ISSUE THREAD

**Issue by rwatts3** [scorpiusjs/core#3]
## Initial Build for Scorpius Core 

**TODO**
- [ ] Integrate Inspinia Admin Theme
- [ ] Build basic layout for the Admin panel 
- [ ] Create routes for Admin Panel
- [ ] Write Tests for Core
- [ ] Create and update documentation for core.
